### ISSUE TITLE
Agid-JWT-TrackingEvidence - payload mandatory fields

### ISSUE THREAD

**Issue by nicolabeghin** [italia/api-padigitale2026-misura1.3.1-uni-afam#212]
Given it's not clear from [documentation](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#il-flusso-in-dettaglio), can you please confirm that in `Agid-JWT-TrackingEvidence` payload it's required to pass over the standard token fields
* `aud`: audience
* `jti`: UUID4
* `iat`: issued 
* `exp`: expiration
?

thanks
nicola

**Comment by nicolabeghin** [comment]
Claims `aud,jti,iat,exp` are mandatory in `Agid-JWT-TrackingEvidence` as per [Linee Guida sull’interoperabilità tecnica delle Pubbliche Amministrazioni – Pattern di sicurezza](https://www.retedigitale.gov.it/documenti/documenti/view?id=137)

ref. https://github.com/link-it/govway/issues/168
![image](https://github.com/user-attachments/assets/f3c4fd24-7166-4bcd-89f6-ac571b7e54f2)
![image](https://github.com/user-attachments/assets/0840ce7d-a92c-4df3-ae90-adf89dd7a816)

**Comment by denismarini** [comment]
Buonasera @nicolabeghin,

Sarebbe consigliabile contattare l’helpdesk di PagoPA al seguente link: [assistenza PagoPA](https://selfcare.pagopa.it/assistenza). In alternativa, se ritieni che la tua problematica possa essere di interesse generale, puoi aprire una issue nel repository GitHub dedicato: [pagopa/pdnd-interop-frontend](https://github.com/pagopa/pdnd-interop-frontend)

Grazie


cc @mfortini

**Comment by denismarini** [comment]
Dear @nicolabeghin,

I’m pleased to hear that you found valuable information for setting up the Govway API Gateway, thank you very much for your contribute. I would like to add that it’s recommended to use the profile [ID_AUTH_REST_01] for Direct Trust with an X.509 certificate over REST in the 1.3.1 UNIAFAM Domain

Thanks

cc @mfortini

**Comment by nicolabeghin** [comment]
Just to confirm: as stated in https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher the is required along with `Bearer?`, right? Also `Agid-JWT-TrackingEvidence` is part of auditing protocol `AUDIT_01`.

> il fruitore fa una richiesta di dati all'erogatore: il fruitore invia quindi una richiesta all'erogatore, inserendo il voucher di PDND Interoperabilità nell'header autorizzativo `Authorization` secondo il flusso standard. Nella stessa chiamata, inserisce in un secondo header chiamato `Agid-JWT-TrackingEvidence` il JWS con le informazioni complementari

**Comment by denismarini** [comment]
Dear @nicolabeghin,

In this project, you don’t need to use the Agid-JWT-TrackingEvidence token. This token is only required for the AUDIT_REST profile, which is used for specific legal use cases. The Audit profile is not needed for this project.

In the guide https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#trasmettere-e-tracciare-dati-complementari-alla-richiesta the second token Agid-JWT-TrackingEvidence is mentioned only to manage the added info in the communication for the audit purpose

I hope I was helpful

**Comment by denismarini** [comment]
You can remove the check in the following screenshot

<img width="700" alt="image" src="https://github.com/user-attachments/assets/e19836a8-410b-411d-825e-5f408737604f">

**Comment by nicolabeghin** [comment]
Thanks it's one check less to perform but we were performing this already. Honestly I'm appalled this wasn't documented as not mandatory since there's no indication otherwise in official documentation ad reported before.

https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher

So just to reiterate: **there's no need to check that additional token ** even if reported in the documentation?

**Comment by denismarini** [comment]
Dear @nicolabeghin,

I confirm that you do not need to check the additional token, Agid-JWT-TrackingEvidence.

Thank you for your feedback. We realize that the current documentation doesn't enough highlight that the standard profile for API 1.3.1 UNIAFAM should be used. Additionally, the AUDIT profile, intended for specific cases, is not enough clarified in the PagoPA documentation. We apologize for this lack of clarity. We will proceed to improve the documentation for notice 1.3.1 and contact PagoPA to request an update that clarifies these aspects, in order to avoid misunderstandings and facilitate the use of the standard flow by designers.

cc @mfortini

**Comment by nicolabeghin** [comment]
Thanks @denismarini I appreciate the transparency. Keep up the good work!

**Comment by nicolabeghin** [comment]
> Hi @nicolabeghin,
> 
> Could you please confirm whether the following screenshot is from the GovWay API Gateway?
> 
> Thanks

cannot see the image sorry!

**Comment by denismarini** [comment]
I am sorry, the following 

<img width="810" alt="image" src="https://github.com/user-attachments/assets/41ea8ea3-b7ac-4241-bd6c-1bf62d9f38f3">

**Comment by nicolabeghin** [comment]
I confirm - please note: to get "Linee Guida Modi Optional" some customizing is required in govway properties

**Comment by denismarini** [comment]
Since each API Gateway has its own settings, it's crucial for the PNRR 1.3.1 UNIAFAM project to configure the API Gateway to communicate using the **basic profile with PDND**, based on the LGModl: Profile ID_AUTH_REST_01. The guide lines in the Modl might not be be mapped 1-1 with the ApiGateway since depend on its design and its user guide. I would like to remind you that using an API gateway is not mandatory for the 1.3.1 UNIAFAM project. Whether or not to use one depends on the software architecture of the system that will integrate with the PDND. Anyway, the GovWay ApiGateway is a good chose for the most of solutions and plus it's delivered by https://developers.italia.it/
